name: twister-spinner
version: '1.0'
summary: Twister Spinner
description: |
  Allows you to play Twister with just two people
confinement: strict 
base: core18
grade: stable
icon: snap/gui/twister-spinner.png

parts:
  desktop-qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - ffmpeg
      - libslang2
  mainapp:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source-type: local
    source: . 
#    requirements: requirements.txt
    stage-packages:
    - python-six
    - python3-pyqt5
    - python3-pydub
  images:
    after: [mainapp]
    plugin: dump 
    source: images 
    organize: 
      '*': images/
  audio:
    after: [mainapp]
    plugin: dump 
    source: audio 
    organize: 
      '*': audio/
apps:
  twister-spinner:
    command: desktop-launch $SNAP/bin/twister-spinner
    environment:
      DISABLE_WAYLAND: 1
    plugs: ['desktop', 'framebuffer', 'camera', 'network', 'home', 'opengl', 'x11','desktop-legacy']